enum DropletSize {
  muitoFinas,
  finas,
  medias,
  grossas,
  muitoGrossas,
  ultraGrossas,
  extremamenteGrossas,
}

enum JetType {
  jatoPlano,
  jatoConico,
  jatoDefletido,
  jatoSolido,
  jatoEstendido,
}

class NozzleSeries {
  final String seriesCode;
  final String fullName;
  final JetType jetType;
  final List<DropletSize> dropletRange;
  final String dropletDescription;
  final List<String> keywords;

  const NozzleSeries({
    required this.seriesCode,
    required this.fullName,
    required this.jetType,
    required this.dropletRange,
    required this.dropletDescription,
    required this.keywords,
  });
}

const List<NozzleSeries> kNozzleSeries = [
  // ═══ CHORRO PLANO ═══
  NozzleSeries(
    seriesCode: 'MUG',
    fullName: 'Magno Ultra Gruesa',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.ultraGrossas],
    dropletDescription: 'Ultra Gruesas',
    keywords: ['MUG', 'MAGNO ULTRA GROSSA'],
  ),
  NozzleSeries(
    seriesCode: 'MUG-SI',
    fullName: 'Magno Ultra Gruesa Sin Inducción de Aire',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.ultraGrossas],
    dropletDescription: 'Ultra Gruesas',
    keywords: ['MUG-SI', 'MUG SI'],
  ),
  NozzleSeries(
    seriesCode: 'MUG-CV',
    fullName: 'Magno Ultra Gruesa Cono Vacío',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.ultraGrossas],
    dropletDescription: 'Ultra Gruesas',
    keywords: ['MUG-CV', 'MUG CV'],
  ),
  NozzleSeries(
    seriesCode: 'APS',
    fullName: 'Aplicación Selectiva',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.ultraGrossas],
    dropletDescription: 'Finas a Ultra Gruesas',
    keywords: ['APS', 'APLICACAO SELETIVA'],
  ),
  NozzleSeries(
    seriesCode: 'BD-AV',
    fullName: 'Baja Deriva Alto Volumen',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.ultraGrossas],
    dropletDescription: 'Finas a Ultra Gruesas',
    keywords: ['BD-AV', 'BAIXA DERIVA ALTO VOLUME'],
  ),
  NozzleSeries(
    seriesCode: 'BD',
    fullName: 'Baja Deriva',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.muitoFinas, DropletSize.extremamenteGrossas],
    dropletDescription: 'Muy Finas a Extremadamente Gruesas',
    keywords: ['BOQUILLA BAJA DERIVA', 'BD 80', 'BD 110', 'BOQUILLA BD'],
  ),
  NozzleSeries(
    seriesCode: 'PB',
    fullName: 'Punta de Barra',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.muitoGrossas],
    dropletDescription: 'Finas a Muy Gruesas',
    keywords: ['PB', 'PONTA DE BARRA'],
  ),
  NozzleSeries(
    seriesCode: 'PB-IA',
    fullName: 'Punta de Barra con Inducción de Aire',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.grossas, DropletSize.ultraGrossas],
    dropletDescription: 'Gruesas a Ultra Gruesas',
    keywords: ['PB-IA', 'PB IA'],
  ),
  NozzleSeries(
    seriesCode: 'ST',
    fullName: 'Super Turbo',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.extremamenteGrossas],
    dropletDescription: 'Finas a Extremadamente Gruesas',
    keywords: ['SUPER TURBO', ' ST '],
  ),
  NozzleSeries(
    seriesCode: 'ST/D',
    fullName: 'Super Turbo Doble',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.medias, DropletSize.muitoGrossas],
    dropletDescription: 'Medias a Muy Gruesas',
    keywords: ['ST/D', 'SUPER TURBO DUPLO'],
  ),
  NozzleSeries(
    seriesCode: 'ST-IA',
    fullName: 'Super Turbo con Inducción de Aire',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.grossas, DropletSize.ultraGrossas],
    dropletDescription: 'Gruesas a Ultra Gruesas',
    keywords: ['ST-IA', 'STIA'],
  ),
  NozzleSeries(
    seriesCode: 'ST-IA/D',
    fullName: 'Super Turbo con Inducción de Aire Doble',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.muitoGrossas],
    dropletDescription: 'Finas a Muy Gruesas',
    keywords: ['ST-IA/D', 'STIA/D'],
  ),
  NozzleSeries(
    seriesCode: 'AD',
    fullName: 'Anti-Deriva',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.grossas],
    dropletDescription: 'Finas a Gruesas',
    keywords: ['ANTIDERIVA', 'ANTI DERIVA', 'ANTI-DERIVA AD', 'BOQUILLAAD'],
  ),
  NozzleSeries(
    seriesCode: 'ADGA',
    fullName: 'Anti-Deriva Gran Ángulo',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.medias],
    dropletDescription: 'Finas a Medias',
    keywords: ['ADGA', 'ANTIDERIVA GRAN ANGULO', 'GRAN ANGULO ADGA'],
  ),
  NozzleSeries(
    seriesCode: 'AD/D',
    fullName: 'Anti-Deriva Doble',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.muitoGrossas],
    dropletDescription: 'Finas a Muy Gruesas',
    keywords: ['AD/D', 'ANTIDERIVA DUPLO'],
  ),
  NozzleSeries(
    seriesCode: 'AD/T',
    fullName: 'Anti-Deriva Triple',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.muitoGrossas],
    dropletDescription: 'Finas a Muy Gruesas',
    keywords: ['AD/T', 'ANTIDERIVA TRIPLO'],
  ),
  NozzleSeries(
    seriesCode: 'AD-IA',
    fullName: 'Anti-Deriva con Inducción de Aire',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.grossas, DropletSize.ultraGrossas],
    dropletDescription: 'Gruesas a Ultra Gruesas',
    keywords: ['AD-IA', 'ADIA'],
  ),
  NozzleSeries(
    seriesCode: 'AD-IA/D',
    fullName: 'Anti-Deriva con Inducción de Aire Doble',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.medias, DropletSize.ultraGrossas],
    dropletDescription: 'Medias a Ultra Gruesas',
    keywords: ['AD-IA/D', 'ADIA/D'],
  ),
  NozzleSeries(
    seriesCode: 'AD-IA/T',
    fullName: 'Anti-Deriva con Inducción de Aire Triple',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.extremamenteGrossas],
    dropletDescription: 'Finas a Extremadamente Gruesas',
    keywords: ['AD-IA/T', 'ADIA/T'],
  ),
  NozzleSeries(
    seriesCode: 'AS7030',
    fullName: 'Asimétrico',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.finas, DropletSize.grossas],
    dropletDescription: 'Finas a Gruesas',
    keywords: ['AS7030', 'ASIMETRICO'],
  ),
  NozzleSeries(
    seriesCode: 'AS-IA7030',
    fullName: 'Asimétrico con Inducción de Aire',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.medias, DropletSize.extremamenteGrossas],
    dropletDescription: 'Medias a Extremadamente Gruesas',
    keywords: ['AS-IA7030', 'ASIA7030'],
  ),
  NozzleSeries(
    seriesCode: 'AS-IA',
    fullName: 'Asimétrico con Inducción de Aire',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.medias, DropletSize.extremamenteGrossas],
    dropletDescription: 'Medias a Extremadamente Gruesas',
    keywords: ['AS-IA', 'ASIA '],
  ),
  NozzleSeries(
    seriesCode: 'MF',
    fullName: 'Magno Fan',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.muitoFinas, DropletSize.medias],
    dropletDescription: 'Muy Finas a Medias',
    keywords: ['MF 0', 'MF 01', 'MF 02', 'MF 03', 'MAGNO FAN', 'BOQUILLA MF'],
  ),
  NozzleSeries(
    seriesCode: 'MD-IA/D',
    fullName: 'Magno Divergente con Inducción de Aire',
    jetType: JetType.jatoPlano,
    dropletRange: [DropletSize.medias, DropletSize.extremamenteGrossas],
    dropletDescription: 'Medias a Extremadamente Gruesas',
    keywords: ['MD-IA/D', 'MDIA/D'],
  ),

  // ═══ CHORRO CÓNICO ═══
  NozzleSeries(
    seriesCode: 'MGA 40',
    fullName: 'Magno Gotas Atomizadas 40°',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.muitoFinas],
    dropletDescription: 'Muy Finas',
    keywords: ['MGA 40', 'MAGNO GOTAS ATOMIZADAS 40'],
  ),
  NozzleSeries(
    seriesCode: 'MGA 60',
    fullName: 'Magno Gotas Atomizadas 60°',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.muitoFinas, DropletSize.finas],
    dropletDescription: 'Muy Finas a Finas',
    keywords: ['MGA 60', 'MAGNO GOTAS ATOMIZADAS 60'],
  ),
  NozzleSeries(
    seriesCode: 'MGA 90',
    fullName: 'Magno Gotas Atomizadas 90°',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.muitoFinas, DropletSize.finas],
    dropletDescription: 'Muy Finas a Finas',
    keywords: ['MGA 90', 'MAGNO GOTAS ATOMIZADAS 90'],
  ),
  NozzleSeries(
    seriesCode: 'MAG CH',
    fullName: 'Magno Cono Lleno',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.muitoFinas, DropletSize.medias],
    dropletDescription: 'Muy Finas a Medias',
    keywords: ['MAG CH', 'CONE CHEIO'],
  ),
  NozzleSeries(
    seriesCode: 'MAG',
    fullName: 'Magno Cono Vacío',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.muitoFinas, DropletSize.finas],
    dropletDescription: 'Muy Finas a Finas',
    keywords: ['BOQUILLA MAG', 'PULVERIZADOR MAG'],
  ),
  NozzleSeries(
    seriesCode: 'CH100',
    fullName: 'Cono Lleno 100°',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.finas, DropletSize.muitoGrossas],
    dropletDescription: 'Finas a Muy Gruesas',
    keywords: ['CH 100', 'CH100', 'CONE CHEIO 100'],
  ),
  NozzleSeries(
    seriesCode: 'BX-AP',
    fullName: 'Baja Presión Alta Penetración',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.muitoFinas, DropletSize.medias],
    dropletDescription: 'Muy Finas a Medias',
    keywords: ['BX-AP', 'BXAP', 'BAIXA PRESSAO'],
  ),
  NozzleSeries(
    seriesCode: 'CV-IA',
    fullName: 'Cono Vacío con Inducción de Aire',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.medias, DropletSize.ultraGrossas],
    dropletDescription: 'Medias a Ultra Gruesas',
    keywords: ['CV-IA', 'CVIA'],
  ),
  NozzleSeries(
    seriesCode: 'MCH-AV',
    fullName: 'Magno Cono Lleno Alto Caudal',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.ultraGrossas],
    dropletDescription: 'Ultra Gruesas',
    keywords: ['MCH-AV', 'MCHAV'],
  ),
  NozzleSeries(
    seriesCode: 'MFC',
    fullName: 'Magno Full Cone',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.finas, DropletSize.grossas],
    dropletDescription: 'Finas a Gruesas',
    keywords: ['MFC', 'MAGNO FULL CONE'],
  ),
  NozzleSeries(
    seriesCode: 'MCV',
    fullName: 'Magno Cono Vacío',
    jetType: JetType.jatoConico,
    dropletRange: [DropletSize.finas, DropletSize.muitoGrossas],
    dropletDescription: 'Finas a Muy Gruesas',
    keywords: ['MCV', 'MAGNO CONE VAZIO'],
  ),

  // ═══ CHORRO DEFLECTADO ═══
  NozzleSeries(
    seriesCode: 'TM-IA',
    fullName: 'Turbo Magno con Inducción de Aire',
    jetType: JetType.jatoDefletido,
    dropletRange: [DropletSize.muitoGrossas, DropletSize.ultraGrossas],
    dropletDescription: 'Muy Gruesas a Ultra Gruesas',
    keywords: ['TM-IA', 'TMIA', 'TURBO MAGNO'],
  ),
  NozzleSeries(
    seriesCode: 'MDC',
    fullName: 'Magno Deflector de Cerámica',
    jetType: JetType.jatoDefletido,
    dropletRange: [DropletSize.finas, DropletSize.ultraGrossas],
    dropletDescription: 'Finas a Ultra Gruesas',
    keywords: ['MDC', 'DEFLETOR CERAMICA', 'MAGNO DEFLETOR'],
  ),
  NozzleSeries(
    seriesCode: 'MJC',
    fullName: 'Magno Chorro de Campo',
    jetType: JetType.jatoDefletido,
    dropletRange: [DropletSize.grossas, DropletSize.extremamenteGrossas],
    dropletDescription: 'Gruesas a Extremadamente Gruesas',
    keywords: ['MJC', 'JATO DE CAMPO'],
  ),
  NozzleSeries(
    seriesCode: 'MD-UG',
    fullName: 'Magno Deflector Ultra Gruesa',
    jetType: JetType.jatoDefletido,
    dropletRange: [DropletSize.ultraGrossas],
    dropletDescription: 'Ultra Gruesas',
    keywords: ['MD-UG', 'MDUG'],
  ),

  // ═══ CHORRO EXTENDIDO ═══
  NozzleSeries(
    seriesCode: 'MJE',
    fullName: 'Magno Chorro Extendido',
    jetType: JetType.jatoEstendido,
    dropletRange: [DropletSize.ultraGrossas],
    dropletDescription: 'Ultra Gruesas',
    keywords: ['MJE', 'JATO ESTENDIDO'],
  ),

  // ═══ CHORRO SÓLIDO ═══
  NozzleSeries(
    seriesCode: 'MJS',
    fullName: 'Magno Chorro Sólido',
    jetType: JetType.jatoSolido,
    dropletRange: [],
    dropletDescription: 'Chorro Sólido',
    keywords: ['MJS', 'JATO SOLIDO'],
  ),
  NozzleSeries(
    seriesCode: 'MJ3',
    fullName: 'Magno Chorro Sólido Tres Orificios',
    jetType: JetType.jatoSolido,
    dropletRange: [],
    dropletDescription: 'Tres Chorros Sólidos',
    keywords: ['MJ3', 'TRES ORIFICIOS'],
  ),
  NozzleSeries(
    seriesCode: 'MJ6',
    fullName: 'Magno Chorro Sólido Seis Orificios',
    jetType: JetType.jatoSolido,
    dropletRange: [],
    dropletDescription: 'Seis Chorros Sólidos',
    keywords: ['MJ6', 'SEIS ORIFICIOS'],
  ),
];
